Add clearCache feature to fastify.view
fastify/point-of-view pull request #202
Opened 2021-01-22 02:08 UTC by savearray2

#### Checklist

- [x] run `npm run test`
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Pull request for the following feature mentioned here: https://github.com/fastify/point-of-view/issues/201
Please let me know if there's anything you would like changed, as it's my first time contributing to fastify.

Thank you :)

2021-01-22 08:02 UTC, mcollina requested changes

2021-01-22 08:02 UTC, mcollina commented on test/test.js
> +  fs.writeFileSync(path.join(templatesFolder, 'cache_clear_test.ejs'), '<html><body><span>123</span></body></<html>')
Can you please use the system temp folder instead?

2021-01-22 08:02 UTC, mcollina commented on test/test.js
> +    t.ok(fastify.view.clearCache)
this assertion is not needed

2021-01-22 08:24 UTC, savearray2 commented
@mcollina 
Thank you for your review. I've made the changes you've requested.
Please let me know if there is anything else you would like updated.

Thanks again :)

2021-01-23 09:44 UTC, Eomm commented on README.md
> +To forcefully clear cache when in production mode, call the ```view.clearCache()``` function.
```suggestion
To forcefully clear cache when in production mode, call the `view.clearCache()` function.
```

2021-01-23 09:44 UTC, Eomm commented on test/test.js
> +      fastify.view.clearCache()
I would add another request before the clear to check:

- call `/view-cache-test` and it loads the file
- call `/view-cache-test` and it hits the cache
- `clearCache`
- call `/view-cache-test` and it loads the file again

2021-01-23 11:19 UTC, savearray2 commented
@Eomm 

Thank you for your input :)
I've made the changes you requested.
Please let me know if there's anything else.

2021-01-25 21:48 UTC, Eomm approved these changes

2021-01-26 20:37 UTC, mcollina approved these changes
lgtm

2021-01-26 20:37 UTC, merged

2024-09-08 21:03 UTC, lilpoozie2005 approved these changes