Add prefix
fastify/point-of-view pull request #204
Opened 2021-01-27 09:11 UTC by alex2844

```
fastify.register(require('../index'), {
  engine: { ejs: ejs },
  ....,
  prefix: 'mobile'
})
fastify.register(require('../index'), {
  engine: { ejs: ejs },
  ....,
  prefix: 'desktop'
})

reply.mobile('index-for-layout.ejs', { text })
reply.desktop('index-for-layout.ejs', { text })
```

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-01-27 10:47 UTC, mcollina requested changes
I would not use `prefix` as a name for this option as it's a common option in fastify plugins to identify a route prefix, e.g. `/v1`. It's best to use a different name to avoid conflicts.

Maybe `propertyName`, `name` or `exposeAs`.

2021-01-27 11:03 UTC, alex2844 commented
I'll be back in a few hours and fix the conflict with the current version

2021-01-27 13:41 UTC, mcollina requested changes
could you please document this in the readme?

2021-01-28 08:34 UTC, mcollina approved these changes
lgtm

2021-01-28 19:29 UTC, zekth approved these changes
lgtm but what about showing the example you described in the issue?
Like having 2 different declarations with different propertynames calling different partials?
```js
fastify.register(require('../index'), {
  engine: { ejs: ejs },
  layout: './templates/layout-mobile.hbs'
  propertyName: 'mobile'
})
fastify.register(require('../index'), {
  engine: { ejs: ejs },
  layout: './templates/layout-desktop.hbs'
  propertyName: 'desktop'
})
```
I think this is a revelant example to showcase this feature

2021-01-28 19:57 UTC, zekth requested changes

2021-01-28 19:57 UTC, zekth commented on README.md
> +Like having 2 different declarations with different propertynames calling different partials?
```suggestion
Like having 2 different declarations with different propertynames calling different partials:
```

2021-01-28 20:33 UTC, zekth approved these changes

2021-01-29 09:49 UTC, merged

2024-09-08 21:02 UTC, lilpoozie2005 approved these changes