Default extension for ejs
fastify/point-of-view pull request #205
Opened 2021-01-29 17:57 UTC by alex2844

index.js
```
require('fastify')()
.register(require('./index'), {
    engine: {
        ejs: require('ejs')
    },
    viewExt: 'html'
})
.get('/', (req, rep) => {
    rep.view('test');
})
.listen(3000);
```

test.html
`<%- include('test2'); %>`

test2.html
`ok`

Error:
`Could not find the include file "test2"`

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-01-29 17:59 UTC, mcollina requested changes
Can you please add a unit test?

2021-01-29 18:01 UTC, alex2844 commented
> Can you please add a unit test?

ok

2021-01-30 17:17 UTC, mcollina approved these changes
lgtm

2021-02-01 08:43 UTC, zekth approved these changes

2021-02-01 11:37 UTC, merged

2024-09-08 21:00 UTC, lilpoozie2005 approved these changes