EJS: Fixed local override of async from true to false
fastify/point-of-view pull request #319
Opened 2022-05-30 17:40 UTC by TTPO100AJIEX

There has been an error overriding async from true to false in the render function. These changes should fix that.
Now it is possible to specify async: true in global options, and async: false as a local option. The overriding behavior now works correctly: local option async: false will be used.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-05-31 06:47 UTC, climba03003 requested changes
You can use nullish operator and it can ensure the `local` take precedence when it has value.

2022-05-31 06:47 UTC, climba03003 commented on index.js
> +        if (opts?.async !== undefined ? opts.async : globalOptions.async) {
```suggestion
        if (opts?.async ?? globalOptions.async) {
```

2022-05-31 06:47 UTC, climba03003 commented on index.js
> +      if (type === 'ejs' && (localOptions.async)) {
```suggestion
      if (type === 'ejs' && (localOptions.async ?? globalOptions.async)) {
```

2022-05-31 07:02 UTC, climba03003 approved these changes
LGTM.

2022-05-31 10:05 UTC, merged

2024-09-08 20:36 UTC, lilpoozie2005 approved these changes