suggestion: await engine to support inline engine import in options
fastify/point-of-view pull request #422
Opened 2024-04-10 15:38 UTC by autopulated

With commonjs it was common to require the engine in the options, and the current readme suggests this usage:

```js
fastify.register(require("@fastify/view"), {  engine: { ejs: require("ejs") } });
```

With modules, the same usage wasn't previously possible, because the inline import returns a promise.

```mjs
app.register(import('@fastify/view'), { engine: { ejs: import('ejs') } })
// results in error later that "engine.compile is not a function"
```

So instead you had to await that import inline, and delay setting up further plugins:
```mjs
app.register(import('@fastify/view'), { engine: { ejs: await import('ejs') } })
```

Since the plugin initialisation is already an async function, it seemed straightforward to just `await` the engine during plugin initialisation instead, which will hopefully allow more plugin loading to occur before blocking on the await.

Is this a good idea? If so I will update the docs as well.

If not we could add validation that the engine is actually an engine (has a .compile function?), to catch this error at plugin initialisation time?

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [-] tests and/or benchmarks are included
- [-] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-04-10 16:38 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2024-04-10 17:09 UTC, autopulated commented
I've added a test using a `.mjs` file in the tests directory (had to explicitly point tap at this).

I'm not sure if this will cause a problem since everything was previously commonjs. If it is then the test could just use require and manually wrap the module in a promise instead?

2024-04-10 17:11 UTC, gurgunday commented
I think `import()` exists in CJS and does the same thing

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

But this is fine

2024-04-10 17:13 UTC, gurgunday commented on package.json
> +    "test:unit": "tap test/*.js test/*.mjs",
LGTM, but can you please leave it as `tap` here add `test/*.{js,mjs}` to the `.taprc` file?

```suggestion
    "test:unit": "tap",
```

2024-04-10 18:23 UTC, gurgunday approved these changes
lgtm

2024-04-11 08:59 UTC, mcollina approved these changes
lgtm

2024-04-11 08:59 UTC, merged